djangoeve/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
	url(r'', include('evedb.urls', namespace='evedb')),
]

evedb/urls.py
from django.conf.urls import url
from django.contrib.auth.views import login
from . import views

urlpatterns = [
	url(r'^$', views.index, name='index'),
	url(r'^git/$', views.git, name='git'),
	url(r'^ss/$', views.ss, name='ss'),
	url(r'^new_token/$', views.new_token, name='new_token'),
	url(r'^logout/$', views.logout_d, name='logout'),
	url(r'^login/$', login, {'template_name': 'evedb/login.html'}, name='login'),
]

evedb/models.py
from django.db import models

class InvGroup(models.Model):
	group_id = models.IntegerField()
	name_ru = models.CharField(max_length=200)
	name_en = models.CharField(max_length=200)
	
	def __str__(self):
		return str(self.group_id)+":"+self.name_ru

class SSToken(models.Model):
	token = models.CharField(max_length=200)
	token_date = models.DateTimeField(auto_now_add=True)
	
	def __str__(self):
		return str(self.token_date)

evedb/forms.py
from django import forms
from .models import SSToken

class TokenForm(forms.ModelForm):
	class Meta:
		model = SSToken
		fields = ['token']
		labels = {'token': ''}
		
class GetImageForm(forms.ModelForm):
	image_id = forms.CharField(max_length=100)		

evedb/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.core.urlresolvers import reverse
from django.contrib.auth import logout, authenticate, login
from django.contrib.auth.decorators import login_required

from .models import SSToken
from .forms import TokenForm, GetImageForm

def index(request):
	return render(request, 'evedb/index.html')
	
@login_required	
def git(request):
	return render(request, 'evedb/git.html')

@login_required
def ss(request):
	return render(request, 'evedb/ss.html')
	
def logout_d(request):
	logout(request)
	return HttpResponseRedirect(reverse('evedb:index'))
	
@login_required
def new_token(request):
	if request.method != 'POST':
		form = TokenForm()
	else:
		form = TokenForm(request.POST)
		if form.is_valid():
			form.save()
			return HttpResponseRedirect(reverse('evedb:ss'))
			
	context = {'form': form}
	return render(request, 'evedb/new_token.html', context)
	
@login_required
def get_image(request):
	if request.method != 'POST':
		form = GetImageForm()
	else:
		form = GetImageForm(request.POST)
		if form.is_valid():
			image_id = request.POST['image_id']
			return HttpResponseRedirect(reverse('evedb:ss'))
			
	context = {'form': form}
	return render(request, 'evedb/ss.html', context)

evedb/templates/evedb/base.html
{% load static %}
{% load bootstrap3 %}
<!DOCTYPE html>
<html lang="{% block lng %}{% endblock lng %}">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <meta name="description" content="{% block description %}{% endblock description %}">
    <link rel="icon" href="{% static 'favicon.ico' %}">
	
    <title>{% block title %}{% endblock title %}</title>

	{% bootstrap_css %}
	
    <link href="{% static 'styles/style.css' %}" rel="stylesheet">

    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
  </head>

  <body>
	<div class="container">
	  <div class="login-row">
		{% if user.is_authenticated %}
			<a class="login-link" href="/logout/">Выйти</a>
		{% else %}
			<a class="login-link" href="{% url 'evedb:login' %}">Войти</a>
		{% endif %}
      </div>	
    <nav class="navbar navbar-default">
      <div class="container-fluid">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="{% url 'evedb:index' %}">EVE DB</a>
        </div>
        <div id="navbar" class="collapse navbar-collapse">
          <ul class="nav navbar-nav">
            <li><a href="#">Группы</a></li>
			<li><a href="#">Предметы</a></li>
			<li><a href="#">Чертежи</a></li>
			{% if user.is_authenticated %}
				<li><a href="/git/">Git</a></li>
				<li><a href="/ss/">ShutterStock</a></li>
			{% endif %}
          </ul>
        </div>
      </div>
    </nav>
	</div>

    <div class="container">
		{% block content %}{% endblock content %}
    </div>

	{% bootstrap_javascript %}	
  </body>
</html>

evedb/templates/evedb/git.html
{% extends "evedb/base.html" %}
{% block lng %}ru{% endblock lng %}
{% block description %}Основные команды для работы с Git{% endblock description %}
{% block title %}Git - EVE DB{% endblock title %}
{% block content %}
      <div class="common-left-template">
        <h1>Работа с Git и полезные материалы</h1>
		Тут будем хранить список всего того, что может пригодиться в работе на EVE DB.
		<h2>Команды Git</h2>
        <ul>
			<li><b>git log</b> - лог действий</li>
			<li><b>git status</b> - проверка текущего статуса проекта</li>
			<li><b>git add --all</b> - подготовка всех изменений к отправке</li>
			<li><b>git commit -m "комментарий"</b> - фиксирование сделанных изменений</li>
			<li><b>git push origin</b> - отправка фиксированных изменений в репозиторий</li>
			<li><b>git pull origin</b> - получений изменений из репозитория</li>
		</ul>
		Репозиторий на GitHub - https://github.com/fowle/djangoeve.git
		<h2>Полезные ссылки</h2>
		<ul>
			<li><a href="http://eax.me/git-commands/">Шпаргалка по Git</a></li>
			<li><a href="https://tutorial.djangogirls.org/ru/">Руководство по Django</a></li>
			<li><a href="http://eax.me/python-virtualenv/">Памятка по virtualenv</a></li>
		</ul>
      </div>
{% endblock content %}

evedb/templates/evedb/index.html
{% extends "evedb/base.html" %}
{% block lng %}ru{% endblock lng %}
{% block description %}Сайт содержит статическую информацию о внутриигровых объектах онлайн игры EVE Online{% endblock description %}
{% block title %}EVE DB - Главная{% endblock title %}
{% block content %}
      <div class="starter-template">
        <h1>База данных внутриигровых предметов EVE Online</h1>
        <p class="lead">Use this document as a way to quickly start any new project.<br> All you get is this text and a mostly barebones HTML document.</p>
      </div>
{% endblock content %}

evedb/templates/evedb/login.html
{% load static %}
{% load bootstrap3 %}
<!DOCTYPE html>
<html lang="ru">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <meta name="description" content="{% block description %}{% endblock description %}">
    <link rel="icon" href="{% static 'favicon.ico' %}">
	
    <title>Авторизация - EVE DB</title>

	{% bootstrap_css %}
	
    <link href="{% static 'styles/style.css' %}" rel="stylesheet">

    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
  </head>

  <body>
	<div class="container">
		<div class="login-row">
			<a class="login-link" href="{% url 'evedb:index' %}">Назад</a>
		</div>
		<form class="form-signin" method="post" action="{% url 'evedb:login' %}">
			{% if form.errors %}
				<p class="bg-danger">Неправильное имя или пароль</p>
			{% endif %}
			{% csrf_token %}
			<label for="placeholder" class="sr-only">Логин</label>
			<input type="text" name="username" id="id_username" class="form-control" placeholder="Логин" required autofocus>
			<label for="password" class="sr-only">Password</label>
			<input type="password" name="password" id="id_password" class="form-control" placeholder="Пароль" required>		
			<button class="btn btn-lg btn-primary btn-block" type="submit">Войти</button>
			<input type="hidden" name="next" value="{% url 'evedb:index' %}" />
		</form>
	</div>
	
	{% bootstrap_javascript %}	
  </body>
</html>

evedb/templates/evedb/new_token.html
{% extends "evedb/base.html" %}
{% block lng %}ru{% endblock lng %}
{% block description %}Основные команды для работы с Git{% endblock description %}
{% block title %}ShutterStock - EVE DB{% endblock title %}
{% block content %}
      <div class="common-left-template">
		<p>Новый токен:</p>
		<form method="post" action="{% url 'evedb:new_token' %}">
			{% csrf_token %}
			{{ form.as_p }}
			<button name="submit">Добавить</button>
		</form>
      </div>
{% endblock content %}

evedb/templates/evedb/ss.html
{% extends "evedb/base.html" %}
{% block lng %}ru{% endblock lng %}
{% block description %}Скачивание изображений с сайта ShutterStock{% endblock description %}
{% block title %}ShutterStock - EVE DB{% endblock title %}
{% block content %}
      <div class="common-left-template">
        <p>Новый токен:</p>
		<form method="post" action="{% url 'evedb:ss' %}">
			{% csrf_token %}
			<label for="placeholder" class="sr-only">ИД картинки</label>
			<input type="text" name="image_id" placeholder="ИД картинки" required autofocus>
			<button name="submit">Скачать</button>
		</form>
		<a href="{% url 'evedb:new_token' %}">Добавить токен</a>
      </div>
{% endblock content %}